name: ScriptedQuests
version: '${version}'
main: net.brian.scriptedquests.ScriptedQuests
api-version: 1.18
commands:
  sQuest:
    aliases:
      - sq
depend:
  - MythicMobs
  - GPS
  - PlayerDataSync
